language: node_js
node_js: stable

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

cache:
  directories:
    - node_modules

before_script:
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 rm s3://$BUCKET --recursive --region=$REGION

before_deploy:
  - "npm install"
  - "gulp build"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: public
  region: $REGION
  on:
    branch: master
